import Banner from '../assets/img/mockPropiedad/banner.webp';
import Logo from '../assets/img/mockPropiedad/logo-white.webp';
import LogoColor from '../assets/img/mockPropiedad/logo-color.webp';
import ImageMain from '../assets/img/mockPropiedad/photo-1.webp';
import Picture1 from '../assets/img/mockPropiedad/photo-2.webp';
import Picture2 from '../assets/img/mockPropiedad/photo-3.webp';
import Picture3 from '../assets/img/mockPropiedad/photo-4.webp';
import Agente from '../assets/img/equipo-3.webp';
import Room from '../assets/img/mockPropiedad/room.webp';

export const DataList = [
	{
		"id": 1,
		"image": "https://strata-sooty.vercel.app/_next/static/media/property-1.d8859e7a.webp",
		"type": "Departamento",
		"price": 2800000,
		"title": "Encanto Roca del Mar",
		"info": "Av del Mar 656, Tellería, 82017 Mazatlán, Sin",
		"zone": "Norte",
		"rooms": "1, 3",
		"bathrooms": "1, 2",
		"models": [
			"Agua",
			"Sol",
			"Coral",
			"Catus",
			"Arena"
		],
		"modelSelect": "Agua",
		"subtitle": "La serenidad del desierto con la frescura del océano",
		"textInfo": "Oasis Ananta es un exclusivo desarrollo frente a la playa en Mazatlán, Sinaloa, que fusiona la serenidad del desierto con la frescura del océano.",
		"text": "Este proyecto ofrece un santuario único donde la elegancia se conecta con la naturaleza, proporcionando una experiencia de vida inigualable con todas las comodidades modernas y un diseño arquitectónico que se integra armoniosamente con el entorno natural.",
		"banner": Banner.src,
		"logo": Logo.src,
		"logoColor": LogoColor.src,
		"description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare ligula ante, molestie congue erat interdum nec. Cras efficitur eget velit eget vulputate. Mauris luctus purus vitae faucibus aliquet.",
		"imageMain": ImageMain.src,
		"pictures": [
			Picture1.src,
			Picture2.src,
			Picture3.src,
			Picture1.src,
		],
		"video": Banner.src,
		"picturesExtra": [
			Picture1.src,
			Picture2.src,
			Picture3.src,
		],
		"imageMainExtra": [
			ImageMain.src,
			ImageMain.src,
		],
		"sizes": {
			"interior": "44 m²",
			"terraza": "5.30 m²",
			"total": "49.30 m²"
		},
		"agente": {
			"id": "1",
			"name": "Lorem ipsum dolor sit amet",
			"image": Agente.src
		},
		"features": [
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
		],
		"amenidades": [
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
		],
		"croquis": Room.src
	},
	{
		"id": 2,
		"image": "https://strata-sooty.vercel.app/_next/static/media/property-2.2d4c1442.webp",
		"type": "Renta",
		"price": 1800000,
		"title": "Encanto Roca del Mar",
		"info": "Av del Mar 656, Tellería, 82017 Mazatlán, Sin",
		"zone": "Sur",
		"rooms": "1, 3",
		"bathrooms": "1, 2",
		"models": [
			"Agua",
			"Sol",
			"Coral",
			"Catus",
			"Arena"
		],
		"modelSelect": "Agua",
		"subtitle": "La serenidad del desierto con la frescura del océano",
		"textInfo": "Oasis Ananta es un exclusivo desarrollo frente a la playa en Mazatlán, Sinaloa, que fusiona la serenidad del desierto con la frescura del océano.",
		"text": "Este proyecto ofrece un santuario único donde la elegancia se conecta con la naturaleza, proporcionando una experiencia de vida inigualable con todas las comodidades modernas y un diseño arquitectónico que se integra armoniosamente con el entorno natural.",
		"banner": Banner.src,
		"logo": Logo.src,
		"logoColor": LogoColor.src,
		"description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare ligula ante, molestie congue erat interdum nec. Cras efficitur eget velit eget vulputate. Mauris luctus purus vitae faucibus aliquet.",
		"imageMain": ImageMain.src,
		"pictures": [
			Picture1.src,
			Picture2.src,
			Picture3.src,
			Picture1.src,
		],
		"video": Banner.src,
		"picturesExtra": [
			Picture1.src,
			Picture2.src,
			Picture3.src,
		],
		"imageMainExtra": [
			ImageMain.src,
			ImageMain.src,
		],
		"sizes": {
			"interior": "44 m²",
			"terraza": "5.30 m²",
			"total": "49.30 m²"
		},
		"agente": {
			"id": "1",
			"name": "Lorem ipsum dolor sit amet",
			"image": Agente.src
		},
		"features": [
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
		],
		"amenidades": [
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
		],
		"croquis": Room.src
	},
	{
		"id": 3,
		"image": "https://strata-sooty.vercel.app/_next/static/media/property-3.ea20f941.webp",
		"type": "Desarrollo",
		"price": 3800000,
		"title": "Encanto Roca del Mar",
		"info": "Av del Mar 656, Tellería, 82017 Mazatlán, Sin",
		"zone": "Centro",
		"rooms": "1, 3",
		"bathrooms": "1, 2",
		"models": [
			"Agua",
			"Sol",
			"Coral",
			"Catus",
			"Arena"
		],
		"modelSelect": "Agua",
		"subtitle": "La serenidad del desierto con la frescura del océano",
		"textInfo": "Oasis Ananta es un exclusivo desarrollo frente a la playa en Mazatlán, Sinaloa, que fusiona la serenidad del desierto con la frescura del océano.",
		"text": "Este proyecto ofrece un santuario único donde la elegancia se conecta con la naturaleza, proporcionando una experiencia de vida inigualable con todas las comodidades modernas y un diseño arquitectónico que se integra armoniosamente con el entorno natural.",
		"banner": Banner.src,
		"logo": Logo.src,
		"logoColor": LogoColor.src,
		"description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare ligula ante, molestie congue erat interdum nec. Cras efficitur eget velit eget vulputate. Mauris luctus purus vitae faucibus aliquet.",
		"imageMain": ImageMain.src,
		"pictures": [
			Picture1.src,
			Picture2.src,
			Picture3.src,
			Picture1.src,
		],
		"video": Banner.src,
		"picturesExtra": [
			Picture1.src,
			Picture2.src,
			Picture3.src,
		],
		"imageMainExtra": [
			ImageMain.src,
			ImageMain.src,
		],
		"sizes": {
			"interior": "44 m²",
			"terraza": "5.30 m²",
			"total": "49.30 m²"
		},
		"agente": {
			"id": "1",
			"name": "Lorem ipsum dolor sit amet",
			"image": Agente.src
		},
		"features": [
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
		],
		"amenidades": [
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
		],
		"croquis": Room.src
	},
	{
		"id": 4,
		"image": "https://strata-sooty.vercel.app/_next/static/media/property-4.75e99f81.webp",
		"type": "Conjunto de casas",
		"price": 2800000,
		"title": "Encanto Roca del Mar",
		"info": "Av del Mar 656, Tellería, 82017 Mazatlán, Sin",
		"zone": "Norte",
		"rooms": "1, 3",
		"bathrooms": "1, 2",
		"models": [
			"Agua",
			"Sol",
			"Coral",
			"Catus",
			"Arena"
		],
		"modelSelect": "Agua",
		"subtitle": "La serenidad del desierto con la frescura del océano",
		"textInfo": "Oasis Ananta es un exclusivo desarrollo frente a la playa en Mazatlán, Sinaloa, que fusiona la serenidad del desierto con la frescura del océano.",
		"text": "Este proyecto ofrece un santuario único donde la elegancia se conecta con la naturaleza, proporcionando una experiencia de vida inigualable con todas las comodidades modernas y un diseño arquitectónico que se integra armoniosamente con el entorno natural.",
		"banner": Banner.src,
		"logo": Logo.src,
		"logoColor": LogoColor.src,
		"description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare ligula ante, molestie congue erat interdum nec. Cras efficitur eget velit eget vulputate. Mauris luctus purus vitae faucibus aliquet.",
		"imageMain": ImageMain.src,
		"pictures": [
			Picture1.src,
			Picture2.src,
			Picture3.src,
			Picture1.src,
		],
		"video": Banner.src,
		"picturesExtra": [
			Picture1.src,
			Picture2.src,
			Picture3.src,
		],
		"imageMainExtra": [
			ImageMain.src,
			ImageMain.src,
		],
		"sizes": {
			"interior": "44 m²",
			"terraza": "5.30 m²",
			"total": "49.30 m²"
		},
		"agente": {
			"id": "1",
			"name": "Lorem ipsum dolor sit amet",
			"image": Agente.src
		},
		"features": [
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
		],
		"amenidades": [
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
		],
		"croquis": Room.src
	},
	{
		"id": 5,
		"image": "https://strata-sooty.vercel.app/_next/static/media/property-5.33e966d3.webp",
		"type": "Preventa",
		"price": 1800000,
		"title": "Encanto Roca del Mar",
		"info": "Av del Mar 656, Tellería, 82017 Mazatlán, Sin",
		"zone": "Alrededores",
		"rooms": "1, 3",
		"bathrooms": "1, 2",
		"models": [
			"Agua",
			"Sol",
			"Coral",
			"Catus",
			"Arena"
		],
		"modelSelect": "Agua",
		"subtitle": "La serenidad del desierto con la frescura del océano",
		"textInfo": "Oasis Ananta es un exclusivo desarrollo frente a la playa en Mazatlán, Sinaloa, que fusiona la serenidad del desierto con la frescura del océano.",
		"text": "Este proyecto ofrece un santuario único donde la elegancia se conecta con la naturaleza, proporcionando una experiencia de vida inigualable con todas las comodidades modernas y un diseño arquitectónico que se integra armoniosamente con el entorno natural.",
		"banner": Banner.src,
		"logo": Logo.src,
		"logoColor": LogoColor.src,
		"description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare ligula ante, molestie congue erat interdum nec. Cras efficitur eget velit eget vulputate. Mauris luctus purus vitae faucibus aliquet.",
		"imageMain": ImageMain.src,
		"pictures": [
			Picture1.src,
			Picture2.src,
			Picture3.src,
			Picture1.src,
		],
		"video": Banner.src,
		"picturesExtra": [
			Picture1.src,
			Picture2.src,
			Picture3.src,
		],
		"imageMainExtra": [
			ImageMain.src,
			ImageMain.src,
		],
		"sizes": {
			"interior": "44 m²",
			"terraza": "5.30 m²",
			"total": "49.30 m²"
		},
		"agente": {
			"id": "1",
			"name": "Lorem ipsum dolor sit amet",
			"image": Agente.src
		},
		"features": [
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
		],
		"amenidades": [
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
		],
		"croquis": Room.src
	},
	{
		"id": 6,
		"image": "https://strata-sooty.vercel.app/_next/static/media/property-6.2d8d3284.webp",
		"type": "Proyecto",
		"price": 3800000,
		"title": "Encanto Roca del Mar",
		"info": "Av del Mar 656, Tellería, 82017 Mazatlán, Sin",
		"zone": "Centro",
		"rooms": "1, 3",
		"bathrooms": "1, 2",
		"models": [
			"Agua",
			"Sol",
			"Coral",
			"Catus",
			"Arena"
		],
		"modelSelect": "Agua",
		"subtitle": "La serenidad del desierto con la frescura del océano",
		"textInfo": "Oasis Ananta es un exclusivo desarrollo frente a la playa en Mazatlán, Sinaloa, que fusiona la serenidad del desierto con la frescura del océano.",
		"text": "Este proyecto ofrece un santuario único donde la elegancia se conecta con la naturaleza, proporcionando una experiencia de vida inigualable con todas las comodidades modernas y un diseño arquitectónico que se integra armoniosamente con el entorno natural.",
		"banner": Banner.src,
		"logo": Logo.src,
		"logoColor": LogoColor.src,
		"description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare ligula ante, molestie congue erat interdum nec. Cras efficitur eget velit eget vulputate. Mauris luctus purus vitae faucibus aliquet.",
		"imageMain": ImageMain.src,
		"pictures": [
			Picture1.src,
			Picture2.src,
			Picture3.src,
			Picture1.src,
		],
		"video": Banner.src,
		"picturesExtra": [
			Picture1.src,
			Picture2.src,
			Picture3.src,
		],
		"imageMainExtra": [
			ImageMain.src,
			ImageMain.src,
		],
		"sizes": {
			"interior": "44 m²",
			"terraza": "5.30 m²",
			"total": "49.30 m²"
		},
		"agente": {
			"id": "1",
			"name": "Lorem ipsum dolor sit amet",
			"image": Agente.src
		},
		"features": [
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
		],
		"amenidades": [
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
		],
		"croquis": Room.src
	},
]

export const formatPrice = (price: number) => {
	return `$${price.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',')}`;
};