export const DataList = [
	{
		"id": 1,
		"image": "https://strata-sooty.vercel.app/_next/static/media/property-1.d8859e7a.webp",
		"type": "Departamento",
		"price": 2800000,
		"title": "Encanto Roca del Mar",
		"info": "Av del Mar 656, Tellería, 82017 Mazatlán, Sin",
		"zone": "Norte",
		"rooms": "1, 3",
		"bathrooms": "1, 2",
		"models": [
			"Agua",
			"Sol",
			"Coral",
			"Catus",
			"Arena"
		],
		"modelSelect": "Agua",
		"subtitle": "La serenidad del desierto con la frescura del océano",
		"textInfo": "Oasis Ananta es un exclusivo desarrollo frente a la playa en Mazatlán, Sinaloa, que fusiona la serenidad del desierto con la frescura del océano.",
		"text": "Este proyecto ofrece un santuario único donde la elegancia se conecta con la naturaleza, proporcionando una experiencia de vida inigualable con todas las comodidades modernas y un diseño arquitectónico que se integra armoniosamente con el entorno natural.",
		"banner": "https://strata-sooty.vercel.app/_next/static/media/banner.b2723c35.webp",
		"logo": "https://strata-sooty.vercel.app/_next/static/media/logo-white.6a821635.webp",
		"logoColor": "https://strata-sooty.vercel.app/_next/static/media/logo-color.db51a7bd.webp",
		"description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare ligula ante, molestie congue erat interdum nec. Cras efficitur eget velit eget vulputate. Mauris luctus purus vitae faucibus aliquet.",
		"imageMain": "https://strata-sooty.vercel.app/_next/static/media/photo-1.1642cffe.webp",
		"pictures": [
			"https://strata-sooty.vercel.app/_next/static/media/photo-2.9a0c2abc.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-3.457131d6.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-4.2e1fb7da.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-2.9a0c2abc.webp",
		],
		"video": "https://strata-sooty.vercel.app/_next/static/media/banner.b2723c35.webp",
		"picturesExtra": [
			"https://strata-sooty.vercel.app/_next/static/media/photo-2.9a0c2abc.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-3.457131d6.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-4.2e1fb7da.webp",
		],
		"imageMainExtra": [
			"https://strata-sooty.vercel.app/_next/static/media/photo-1.1642cffe.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-1.1642cffe.webp",
		],
		"sizes": {
			"interior": "44 m²",
			"terraza": "5.30 m²",
			"total": "49.30 m²"
		},
		"agente": {
			"id": "1",
			"name": "Lorem ipsum dolor sit amet",
			"image": "https://strata-sooty.vercel.app/_next/static/media/equipo-3.8feb4d7b.webp"
		},
		"features": [
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
		],
		"amenidades": [
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
		],
		"croquis": "https://strata-sooty.vercel.app/_next/static/media/room.16b3ba1d.webp"
	},
	{
		"id": 2,
		"image": "https://strata-sooty.vercel.app/_next/static/media/property-2.2d4c1442.webp",
		"type": "Renta",
		"price": 1800000,
		"title": "Encanto Roca del Mar",
		"info": "Av del Mar 656, Tellería, 82017 Mazatlán, Sin",
		"zone": "Sur",
		"rooms": "1, 3",
		"bathrooms": "1, 2",
		"models": [
			"Agua",
			"Sol",
			"Coral",
			"Catus",
			"Arena"
		],
		"modelSelect": "Agua",
		"subtitle": "La serenidad del desierto con la frescura del océano",
		"textInfo": "Oasis Ananta es un exclusivo desarrollo frente a la playa en Mazatlán, Sinaloa, que fusiona la serenidad del desierto con la frescura del océano.",
		"text": "Este proyecto ofrece un santuario único donde la elegancia se conecta con la naturaleza, proporcionando una experiencia de vida inigualable con todas las comodidades modernas y un diseño arquitectónico que se integra armoniosamente con el entorno natural.",
		"banner": "https://strata-sooty.vercel.app/_next/static/media/banner.b2723c35.webp",
		"logo": "https://strata-sooty.vercel.app/_next/static/media/logo-white.6a821635.webp",
		"logoColor": "https://strata-sooty.vercel.app/_next/static/media/logo-color.db51a7bd.webp",
		"description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare ligula ante, molestie congue erat interdum nec. Cras efficitur eget velit eget vulputate. Mauris luctus purus vitae faucibus aliquet.",
		"imageMain": "https://strata-sooty.vercel.app/_next/static/media/photo-1.1642cffe.webp",
		"pictures": [
			"https://strata-sooty.vercel.app/_next/static/media/photo-2.9a0c2abc.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-3.457131d6.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-4.2e1fb7da.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-2.9a0c2abc.webp",
		],
		"video": "https://strata-sooty.vercel.app/_next/static/media/banner.b2723c35.webp",
		"picturesExtra": [
			"https://strata-sooty.vercel.app/_next/static/media/photo-2.9a0c2abc.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-3.457131d6.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-4.2e1fb7da.webp",
		],
		"imageMainExtra": [
			"https://strata-sooty.vercel.app/_next/static/media/photo-1.1642cffe.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-1.1642cffe.webp",
		],
		"sizes": {
			"interior": "44 m²",
			"terraza": "5.30 m²",
			"total": "49.30 m²"
		},
		"agente": {
			"id": "1",
			"name": "Lorem ipsum dolor sit amet",
			"image": "https://strata-sooty.vercel.app/_next/static/media/equipo-3.8feb4d7b.webp"
		},
		"features": [
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
		],
		"amenidades": [
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
		],
		"croquis": "https://strata-sooty.vercel.app/_next/static/media/room.16b3ba1d.webp"
	},
	{
		"id": 3,
		"image": "https://strata-sooty.vercel.app/_next/static/media/property-3.ea20f941.webp",
		"type": "Desarrollo",
		"price": 3800000,
		"title": "Encanto Roca del Mar",
		"info": "Av del Mar 656, Tellería, 82017 Mazatlán, Sin",
		"zone": "Centro",
		"rooms": "1, 3",
		"bathrooms": "1, 2",
		"models": [
			"Agua",
			"Sol",
			"Coral",
			"Catus",
			"Arena"
		],
		"modelSelect": "Agua",
		"subtitle": "La serenidad del desierto con la frescura del océano",
		"textInfo": "Oasis Ananta es un exclusivo desarrollo frente a la playa en Mazatlán, Sinaloa, que fusiona la serenidad del desierto con la frescura del océano.",
		"text": "Este proyecto ofrece un santuario único donde la elegancia se conecta con la naturaleza, proporcionando una experiencia de vida inigualable con todas las comodidades modernas y un diseño arquitectónico que se integra armoniosamente con el entorno natural.",
		"banner": "https://strata-sooty.vercel.app/_next/static/media/banner.b2723c35.webp",
		"logo": "https://strata-sooty.vercel.app/_next/static/media/logo-white.6a821635.webp",
		"logoColor": "https://strata-sooty.vercel.app/_next/static/media/logo-color.db51a7bd.webp",
		"description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare ligula ante, molestie congue erat interdum nec. Cras efficitur eget velit eget vulputate. Mauris luctus purus vitae faucibus aliquet.",
		"imageMain": "https://strata-sooty.vercel.app/_next/static/media/photo-1.1642cffe.webp",
		"pictures": [
			"https://strata-sooty.vercel.app/_next/static/media/photo-2.9a0c2abc.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-3.457131d6.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-4.2e1fb7da.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-2.9a0c2abc.webp",
		],
		"video": "https://strata-sooty.vercel.app/_next/static/media/banner.b2723c35.webp",
		"picturesExtra": [
			"https://strata-sooty.vercel.app/_next/static/media/photo-2.9a0c2abc.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-3.457131d6.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-4.2e1fb7da.webp",
		],
		"imageMainExtra": [
			"https://strata-sooty.vercel.app/_next/static/media/photo-1.1642cffe.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-1.1642cffe.webp",
		],
		"sizes": {
			"interior": "44 m²",
			"terraza": "5.30 m²",
			"total": "49.30 m²"
		},
		"agente": {
			"id": "1",
			"name": "Lorem ipsum dolor sit amet",
			"image": "https://strata-sooty.vercel.app/_next/static/media/equipo-3.8feb4d7b.webp"
		},
		"features": [
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
		],
		"amenidades": [
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
		],
		"croquis": "https://strata-sooty.vercel.app/_next/static/media/room.16b3ba1d.webp"
	},
	{
		"id": 4,
		"image": "https://strata-sooty.vercel.app/_next/static/media/property-4.75e99f81.webp",
		"type": "Conjunto de casas",
		"price": 2800000,
		"title": "Encanto Roca del Mar",
		"info": "Av del Mar 656, Tellería, 82017 Mazatlán, Sin",
		"zone": "Norte",
		"rooms": "1, 3",
		"bathrooms": "1, 2",
		"models": [
			"Agua",
			"Sol",
			"Coral",
			"Catus",
			"Arena"
		],
		"modelSelect": "Agua",
		"subtitle": "La serenidad del desierto con la frescura del océano",
		"textInfo": "Oasis Ananta es un exclusivo desarrollo frente a la playa en Mazatlán, Sinaloa, que fusiona la serenidad del desierto con la frescura del océano.",
		"text": "Este proyecto ofrece un santuario único donde la elegancia se conecta con la naturaleza, proporcionando una experiencia de vida inigualable con todas las comodidades modernas y un diseño arquitectónico que se integra armoniosamente con el entorno natural.",
		"banner": "https://strata-sooty.vercel.app/_next/static/media/banner.b2723c35.webp",
		"logo": "https://strata-sooty.vercel.app/_next/static/media/logo-white.6a821635.webp",
		"logoColor": "https://strata-sooty.vercel.app/_next/static/media/logo-color.db51a7bd.webp",
		"description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare ligula ante, molestie congue erat interdum nec. Cras efficitur eget velit eget vulputate. Mauris luctus purus vitae faucibus aliquet.",
		"imageMain": "https://strata-sooty.vercel.app/_next/static/media/photo-1.1642cffe.webp",
		"pictures": [
			"https://strata-sooty.vercel.app/_next/static/media/photo-2.9a0c2abc.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-3.457131d6.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-4.2e1fb7da.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-2.9a0c2abc.webp",
		],
		"video": "https://strata-sooty.vercel.app/_next/static/media/banner.b2723c35.webp",
		"picturesExtra": [
			"https://strata-sooty.vercel.app/_next/static/media/photo-2.9a0c2abc.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-3.457131d6.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-4.2e1fb7da.webp",
		],
		"imageMainExtra": [
			"https://strata-sooty.vercel.app/_next/static/media/photo-1.1642cffe.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-1.1642cffe.webp",
		],
		"sizes": {
			"interior": "44 m²",
			"terraza": "5.30 m²",
			"total": "49.30 m²"
		},
		"agente": {
			"id": "1",
			"name": "Lorem ipsum dolor sit amet",
			"image": "https://strata-sooty.vercel.app/_next/static/media/equipo-3.8feb4d7b.webp"
		},
		"features": [
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
		],
		"amenidades": [
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
		],
		"croquis": "https://strata-sooty.vercel.app/_next/static/media/room.16b3ba1d.webp"
	},
	{
		"id": 5,
		"image": "https://strata-sooty.vercel.app/_next/static/media/property-5.33e966d3.webp",
		"type": "Preventa",
		"price": 1800000,
		"title": "Encanto Roca del Mar",
		"info": "Av del Mar 656, Tellería, 82017 Mazatlán, Sin",
		"zone": "Alrededores",
		"rooms": "1, 3",
		"bathrooms": "1, 2",
		"models": [
			"Agua",
			"Sol",
			"Coral",
			"Catus",
			"Arena"
		],
		"modelSelect": "Agua",
		"subtitle": "La serenidad del desierto con la frescura del océano",
		"textInfo": "Oasis Ananta es un exclusivo desarrollo frente a la playa en Mazatlán, Sinaloa, que fusiona la serenidad del desierto con la frescura del océano.",
		"text": "Este proyecto ofrece un santuario único donde la elegancia se conecta con la naturaleza, proporcionando una experiencia de vida inigualable con todas las comodidades modernas y un diseño arquitectónico que se integra armoniosamente con el entorno natural.",
		"banner": "https://strata-sooty.vercel.app/_next/static/media/banner.b2723c35.webp",
		"logo": "https://strata-sooty.vercel.app/_next/static/media/logo-white.6a821635.webp",
		"logoColor": "https://strata-sooty.vercel.app/_next/static/media/logo-color.db51a7bd.webp",
		"description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare ligula ante, molestie congue erat interdum nec. Cras efficitur eget velit eget vulputate. Mauris luctus purus vitae faucibus aliquet.",
		"imageMain": "https://strata-sooty.vercel.app/_next/static/media/photo-1.1642cffe.webp",
		"pictures": [
			"https://strata-sooty.vercel.app/_next/static/media/photo-2.9a0c2abc.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-3.457131d6.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-4.2e1fb7da.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-2.9a0c2abc.webp",
		],
		"video": "https://strata-sooty.vercel.app/_next/static/media/banner.b2723c35.webp",
		"picturesExtra": [
			"https://strata-sooty.vercel.app/_next/static/media/photo-2.9a0c2abc.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-3.457131d6.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-4.2e1fb7da.webp",
		],
		"imageMainExtra": [
			"https://strata-sooty.vercel.app/_next/static/media/photo-1.1642cffe.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-1.1642cffe.webp",
		],
		"sizes": {
			"interior": "44 m²",
			"terraza": "5.30 m²",
			"total": "49.30 m²"
		},
		"agente": {
			"id": "1",
			"name": "Lorem ipsum dolor sit amet",
			"image": "https://strata-sooty.vercel.app/_next/static/media/equipo-3.8feb4d7b.webp"
		},
		"features": [
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
		],
		"amenidades": [
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
		],
		"croquis": "https://strata-sooty.vercel.app/_next/static/media/room.16b3ba1d.webp"
	},
	{
		"id": 6,
		"image": "https://strata-sooty.vercel.app/_next/static/media/property-6.2d8d3284.webp",
		"type": "Proyecto",
		"price": 3800000,
		"title": "Encanto Roca del Mar",
		"info": "Av del Mar 656, Tellería, 82017 Mazatlán, Sin",
		"zone": "Centro",
		"rooms": "1, 3",
		"bathrooms": "1, 2",
		"models": [
			"Agua",
			"Sol",
			"Coral",
			"Catus",
			"Arena"
		],
		"modelSelect": "Agua",
		"subtitle": "La serenidad del desierto con la frescura del océano",
		"textInfo": "Oasis Ananta es un exclusivo desarrollo frente a la playa en Mazatlán, Sinaloa, que fusiona la serenidad del desierto con la frescura del océano.",
		"text": "Este proyecto ofrece un santuario único donde la elegancia se conecta con la naturaleza, proporcionando una experiencia de vida inigualable con todas las comodidades modernas y un diseño arquitectónico que se integra armoniosamente con el entorno natural.",
		"banner": "https://strata-sooty.vercel.app/_next/static/media/banner.b2723c35.webp",
		"logo": "https://strata-sooty.vercel.app/_next/static/media/logo-white.6a821635.webp",
		"logoColor": "https://strata-sooty.vercel.app/_next/static/media/logo-color.db51a7bd.webp",
		"description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare ligula ante, molestie congue erat interdum nec. Cras efficitur eget velit eget vulputate. Mauris luctus purus vitae faucibus aliquet.",
		"imageMain": "https://strata-sooty.vercel.app/_next/static/media/photo-1.1642cffe.webp",
		"pictures": [
			"https://strata-sooty.vercel.app/_next/static/media/photo-2.9a0c2abc.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-3.457131d6.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-4.2e1fb7da.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-2.9a0c2abc.webp",
		],
		"video": "https://strata-sooty.vercel.app/_next/static/media/banner.b2723c35.webp",
		"picturesExtra": [
			"https://strata-sooty.vercel.app/_next/static/media/photo-2.9a0c2abc.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-3.457131d6.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-4.2e1fb7da.webp",
		],
		"imageMainExtra": [
			"https://strata-sooty.vercel.app/_next/static/media/photo-1.1642cffe.webp",
			"https://strata-sooty.vercel.app/_next/static/media/photo-1.1642cffe.webp",
		],
		"sizes": {
			"interior": "44 m²",
			"terraza": "5.30 m²",
			"total": "49.30 m²"
		},
		"agente": {
			"id": "1",
			"name": "Lorem ipsum dolor sit amet",
			"image": "https://strata-sooty.vercel.app/_next/static/media/equipo-3.8feb4d7b.webp"
		},
		"features": [
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
		],
		"amenidades": [
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
			"Interior",
			"Terraza",
			"Total",
		],
		"croquis": "https://strata-sooty.vercel.app/_next/static/media/room.16b3ba1d.webp"
	},
]

export const formatPrice = (price: number) => {
	return `$${price.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',')}`;
};